export const notTitleCase = /\b[a-z]/;

export const alpha = /^[a-zA-Z ]+$/;

export const campAbbreviations = {
    BDPW: 'Baylor',
    CNDI: 'Berkeley (CNDI)',
    BDL: 'Boston Debate League',
    CDL: 'Chicago Debate League',
    DDI: 'Dartmouth DDI',
    DDIx: 'Dartmouth DDIx',
    ENDI: 'Emory (ENDI)',
    GDS: 'Georgetown (GDS)',
    UGA: 'Georgia',
    GMDI: 'George Mason (GMDI)',
    GDI: 'Gonzaga (GDI)',
    HDC: 'Harvard',
    HSS: 'Hoya-Spartan Scholars',
    JDI: 'Kansas (JDI)',
    MGC: 'Mean Green Comet',
    UM7: 'Michigan (7-week)',
    UMC: 'Michigan (Classic)',
    MNDI: 'Michigan (MNDI)',
    SDI: 'Michigan State (SDI)',
    MSDI: 'Missouri State (MSDI)',
    MGF: 'MoneyGram Foundation',
    NSD: 'National Symposium for Debate',
    NAUDL: 'NAUDL',
    NDI: 'Nebraska (NDI)',
    NHSI: 'Northwestern (NHSI)',
    SSDI: 'Samford',
    SCDI: 'Sun Country (SCDI)',
    UMKC: 'UMKC',
    UTNIF: 'Texas (UTNIF)',
    UNT: 'North Texas (UNT)',
    UTD: 'UT Dallas (UTD)',
    TDI: 'The Debate Intensive',
    RKS: 'Wake Forest (RKS)',
    WSDI: 'Weber State (WSDI)',
    WYO: 'Wyoming',
};

export const campDisplayName = {
    BDPW: 'Baylor',
    CNDI: 'CNDI',
    BDL: 'BDL',
    CDL: 'CDL',
    DDI: 'DDI',
    DDIx: 'DDIx',
    ENDI: 'Emory',
    GDS: 'Georgetown',
    UGA: 'Georgia',
    GMDI: 'George Mason',
    GDI: 'GDI',
    HDC: 'Harvard',
    HSS: 'HSS',
    JDI: 'JDI',
    MGC: 'Mean Green',
    UM7: 'Michigan 7',
    UMC: 'Michigan Classic',
    MNDI: 'MNDI',
    SDI: 'SDI',
    MSDI: 'MSDI',
    MGF: 'MoneyGram',
    NSD: 'NSD',
    NAUDL: 'NAUDL',
    NDI: 'NDI',
    NHSI: 'Northwestern',
    SSDI: 'Samford',
    SCDI: 'SCDI',
    UMKC: 'UMKC',
    UTNIF: 'UTNIF',
    UNT: 'UNT',
    UTD: 'UTD',
    TDI: 'TDI',
    RKS: 'Wake',
    WSDI: 'WSDI',
    WYO: 'Wyoming',
};

export const tagAbbreviations = {
    aff: 'Affirmatives',
    neg: 'Case Negatives',
    cp: 'Counterplans',
    da: 'Disadvantages',
    impact: 'Impact Files',
    atk: 'Kritik Answers',
    k: 'Kritiks',
    ld: 'Lincoln Douglas',
    pol: 'Politics',
    pf: 'Public Forum',
    th: 'Theory',
    t: 'Topicality',
};

export default null;
