name: Caselist CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CI: true
    TZ: "America/Chicago"
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 18.2.0

    - name: Install packages
      run: |
        cd client && npm install

    - name: Lint
      run: |
        cd client && npm run lint

    - name: Test
      run: |
        cd client && npm run test:ci

    - name: If tests passed change icon
      if: success()
      run: echo "SLACK_ICON=:white_check_mark:" >> $GITHUB_ENV

    - name: Send slack notification
      if: always()
      uses: speechanddebate/action-slack-notify@master

  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 18.2.0

    - name: Install packages
      run: |
        cd server && npm install

    - name: Lint
      run: |
        cd server && npm run lint

    - name: If tests passed change icon
      if: success()
      run: echo "SLACK_ICON=:white_check_mark:" >> $GITHUB_ENV

    - name: Send slack notification
      if: always()
      uses: speechanddebate/action-slack-notify@master
